GET http://localhost:8889/hello
Accept: application/json

###
POST http://localhost:8889/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST

###
GET http://localhost:8889/list
Accept: application/json